openapi: 3.0.1
info:
  description: "Get security updates programmatically using this RESTful API. Sample\
    \ client code is available on the [Microsoft Security Updates GitHub](https://github.com/microsoft/MSRC-Microsoft-Security-Updates-API).\
    \ For more details, please visit [msrc.microsoft.com/update-guide](https://msrc.microsoft.com/update-guide).\r\
    \n\r\n_**NOTE: If you're looking for the Engage API (CARS), please refer to the\
    \ new [Abuse Reporting developer portal](https://msrc.microsoft.com/report/developer).**_"
  title: MSRC CVRF API
  version: v2
servers:
- url: https://api.msrc.microsoft.com/cvrf/v2.0
paths:
  /cvrf/{id}:
    get:
      description: "Get detailed Microsoft security update, formatted according to\
        \ the [Common Vulnerability Reporting\r\nFramework](http://www.icasi.org/cvrf/).\
        \ MSRC investigates all reports of\r\nsecurity vulnerabilities affecting Microsoft\
        \ products and services, and provides these updates as part of the\r\nongoing\
        \ effort to help you manage security risks and help keep your systems protected."
      operationId: Cvrf_GetCvrf
      parameters:
      - description: CVRF document ID (yyyy-mmm)
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cvrfdoc'
            text/json:
              schema:
                $ref: '#/components/schemas/cvrfdoc'
            application/xml:
              schema:
                $ref: '#/components/schemas/cvrfdoc'
            text/xml:
              schema:
                $ref: '#/components/schemas/cvrfdoc'
          description: OK
        "400":
          content: {}
          description: Bad Request
        "401":
          content: {}
          description: Unauthorized
        "404":
          content: {}
          description: Not Found
        "500":
          content: {}
          description: Internal Server Error
      summary: Get security update details in CVRF format
      tags:
      - Get Security Updates
  /updates:
    get:
      description: Get a list of all Microsoft security updates. Each includes a link
        to the update details, formatted according to the [Common Vulnerability Reporting
        Framework](https://www.icasi.org/cvrf). This list can be manipulated using
        [OData URL filtering](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752356)
        on current and initial release dates.
      operationId: Updates_GetUpdates
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: OK
        "400":
          content: {}
          description: Bad Request
        "401":
          content: {}
          description: Unauthorized
        "500":
          content: {}
          description: Internal Server Error
      summary: Get all security update summaries
      tags:
      - Get Security Updates
  /Updates('{key}'):
    get:
      description: "Get a list of Microsoft security updates by update ID, vulnerability\
        \ ID ([CVE](https://cve.mitre.org/about)), or year. Each includes a link to\
        \ the update details, formatted according to the [Common Vulnerability Reporting\
        \ Framework](https://www.icasi.org/cvrf). This list can be manipulated using\
        \ [OData URL filtering](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752356)\
        \ on current and initial release dates.\r\n\r\nNOTE: this endpoint is case-sensitive."
      operationId: Updates_GetUpdatesByKey
      parameters:
      - description: update ID (yyyy-mmm), vulnerability ID (CVE number), or year
          (yyyy)
        in: path
        name: key
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: OK
        "400":
          content: {}
          description: Bad Request
        "401":
          content: {}
          description: Unauthorized
        "404":
          content: {}
          description: Not Found
        "500":
          content: {}
          description: Internal Server Error
      summary: Get security update summaries by key
      tags:
      - Get Security Updates
components:
  schemas:
    cvrfdoc:
      example:
        AggregateSeverity:
          Value: Value
          lang: lang
          Namespace: Namespace
        Acknowledgments:
        - Organization:
          - Value: Value
            lang: lang
          - Value: Value
            lang: lang
          Description:
            Value: Value
            lang: lang
          URL:
          - URL
          - URL
          Name:
          - Value: Value
            lang: lang
          - Value: Value
            lang: lang
        - Organization:
          - Value: Value
            lang: lang
          - Value: Value
            lang: lang
          Description:
            Value: Value
            lang: lang
          URL:
          - URL
          - URL
          Name:
          - Value: Value
            lang: lang
          - Value: Value
            lang: lang
        DocumentPublisher:
          Type: 0
          ContactDetails:
            Value: Value
            lang: lang
          VendorID: VendorID
          IssuingAuthority:
            Value: Value
            lang: lang
        DocumentType:
          Value: Value
          lang: lang
        DocumentNotes:
        - Type: 1
          Audience: Audience
          Ordinal: Ordinal
          Value: Value
          Title: Title
          lang: lang
        - Type: 1
          Audience: Audience
          Ordinal: Ordinal
          Value: Value
          Title: Title
          lang: lang
        DocumentDistribution:
          Value: Value
          lang: lang
        Vulnerability:
        - Threats:
          - Type: 4
            Description:
              Value: Value
              lang: lang
            ProductID:
            - ProductID
            - ProductID
            DateSpecified: true
            Date: 2000-01-23T04:56:07.000+00:00
            GroupID:
            - GroupID
            - GroupID
          - Type: 4
            Description:
              Value: Value
              lang: lang
            ProductID:
            - ProductID
            - ProductID
            DateSpecified: true
            Date: 2000-01-23T04:56:07.000+00:00
            GroupID:
            - GroupID
            - GroupID
          Involvements:
          - Status: 3
            Description:
              Value: Value
              lang: lang
            Party: 9
          - Status: 3
            Description:
              Value: Value
              lang: lang
            Party: 9
          ProductStatuses:
          - Type: 2
            ProductID:
            - ProductID
            - ProductID
          - Type: 2
            ProductID:
            - ProductID
            - ProductID
          ReleaseDateSpecified: true
          Title:
            Value: Value
            lang: lang
          Remediations:
          - Description:
              Value: Value
              lang: lang
            RestartRequired:
              Value: Value
              lang: lang
            SubType: SubType
            AffectedFiles:
            - FilePath: FilePath
              FileArchitecture: FileArchitecture
              FileName: FileName
              FileVersion: FileVersion
              FileLastModified: 2000-01-23T04:56:07.000+00:00
              ProductId: ProductId
            - FilePath: FilePath
              FileArchitecture: FileArchitecture
              FileName: FileName
              FileVersion: FileVersion
              FileLastModified: 2000-01-23T04:56:07.000+00:00
              ProductId: ProductId
            Supercedence: Supercedence
            ProductID:
            - ProductID
            - ProductID
            DateSpecified: true
            URL: URL
            Date: 2000-01-23T04:56:07.000+00:00
            GroupID:
            - GroupID
            - GroupID
            Type: 1
            Entitlement:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
            FixedBuild: FixedBuild
          - Description:
              Value: Value
              lang: lang
            RestartRequired:
              Value: Value
              lang: lang
            SubType: SubType
            AffectedFiles:
            - FilePath: FilePath
              FileArchitecture: FileArchitecture
              FileName: FileName
              FileVersion: FileVersion
              FileLastModified: 2000-01-23T04:56:07.000+00:00
              ProductId: ProductId
            - FilePath: FilePath
              FileArchitecture: FileArchitecture
              FileName: FileName
              FileVersion: FileVersion
              FileLastModified: 2000-01-23T04:56:07.000+00:00
              ProductId: ProductId
            Supercedence: Supercedence
            ProductID:
            - ProductID
            - ProductID
            DateSpecified: true
            URL: URL
            Date: 2000-01-23T04:56:07.000+00:00
            GroupID:
            - GroupID
            - GroupID
            Type: 1
            Entitlement:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
            FixedBuild: FixedBuild
          ReleaseDate: 2000-01-23T04:56:07.000+00:00
          CWE:
          - Value: Value
            ID: ID
            lang: lang
          - Value: Value
            ID: ID
            lang: lang
          CVE: CVE
          CVSSScoreSets:
          - TemporalScore: 1.2315135367772556
            EnvironmentalScore: 1.0246457001441578
            ProductID:
            - ProductID
            - ProductID
            BaseScore: 7.386281948385884
            Vector: Vector
          - TemporalScore: 1.2315135367772556
            EnvironmentalScore: 1.0246457001441578
            ProductID:
            - ProductID
            - ProductID
            BaseScore: 7.386281948385884
            Vector: Vector
          Acknowledgments:
          - Organization:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
            Description:
              Value: Value
              lang: lang
            URL:
            - URL
            - URL
            Name:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
          - Organization:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
            Description:
              Value: Value
              lang: lang
            URL:
            - URL
            - URL
            Name:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
          DiscoveryDate: 2000-01-23T04:56:07.000+00:00
          RevisionHistory:
          - Description:
              Value: Value
              lang: lang
            Number: Number
            Date: 2000-01-23T04:56:07.000+00:00
          - Description:
              Value: Value
              lang: lang
            Number: Number
            Date: 2000-01-23T04:56:07.000+00:00
          References:
          - Type: 6
            Description:
              Value: Value
              lang: lang
            URL: URL
          - Type: 6
            Description:
              Value: Value
              lang: lang
            URL: URL
          Ordinal: Ordinal
          DiscoveryDateSpecified: true
          ID:
            Value: Value
            SystemName: SystemName
          Notes:
          - Type: 7
            Audience: Audience
            Ordinal: Ordinal
            Value: Value
            Title: Title
            lang: lang
          - Type: 7
            Audience: Audience
            Ordinal: Ordinal
            Value: Value
            Title: Title
            lang: lang
        - Threats:
          - Type: 4
            Description:
              Value: Value
              lang: lang
            ProductID:
            - ProductID
            - ProductID
            DateSpecified: true
            Date: 2000-01-23T04:56:07.000+00:00
            GroupID:
            - GroupID
            - GroupID
          - Type: 4
            Description:
              Value: Value
              lang: lang
            ProductID:
            - ProductID
            - ProductID
            DateSpecified: true
            Date: 2000-01-23T04:56:07.000+00:00
            GroupID:
            - GroupID
            - GroupID
          Involvements:
          - Status: 3
            Description:
              Value: Value
              lang: lang
            Party: 9
          - Status: 3
            Description:
              Value: Value
              lang: lang
            Party: 9
          ProductStatuses:
          - Type: 2
            ProductID:
            - ProductID
            - ProductID
          - Type: 2
            ProductID:
            - ProductID
            - ProductID
          ReleaseDateSpecified: true
          Title:
            Value: Value
            lang: lang
          Remediations:
          - Description:
              Value: Value
              lang: lang
            RestartRequired:
              Value: Value
              lang: lang
            SubType: SubType
            AffectedFiles:
            - FilePath: FilePath
              FileArchitecture: FileArchitecture
              FileName: FileName
              FileVersion: FileVersion
              FileLastModified: 2000-01-23T04:56:07.000+00:00
              ProductId: ProductId
            - FilePath: FilePath
              FileArchitecture: FileArchitecture
              FileName: FileName
              FileVersion: FileVersion
              FileLastModified: 2000-01-23T04:56:07.000+00:00
              ProductId: ProductId
            Supercedence: Supercedence
            ProductID:
            - ProductID
            - ProductID
            DateSpecified: true
            URL: URL
            Date: 2000-01-23T04:56:07.000+00:00
            GroupID:
            - GroupID
            - GroupID
            Type: 1
            Entitlement:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
            FixedBuild: FixedBuild
          - Description:
              Value: Value
              lang: lang
            RestartRequired:
              Value: Value
              lang: lang
            SubType: SubType
            AffectedFiles:
            - FilePath: FilePath
              FileArchitecture: FileArchitecture
              FileName: FileName
              FileVersion: FileVersion
              FileLastModified: 2000-01-23T04:56:07.000+00:00
              ProductId: ProductId
            - FilePath: FilePath
              FileArchitecture: FileArchitecture
              FileName: FileName
              FileVersion: FileVersion
              FileLastModified: 2000-01-23T04:56:07.000+00:00
              ProductId: ProductId
            Supercedence: Supercedence
            ProductID:
            - ProductID
            - ProductID
            DateSpecified: true
            URL: URL
            Date: 2000-01-23T04:56:07.000+00:00
            GroupID:
            - GroupID
            - GroupID
            Type: 1
            Entitlement:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
            FixedBuild: FixedBuild
          ReleaseDate: 2000-01-23T04:56:07.000+00:00
          CWE:
          - Value: Value
            ID: ID
            lang: lang
          - Value: Value
            ID: ID
            lang: lang
          CVE: CVE
          CVSSScoreSets:
          - TemporalScore: 1.2315135367772556
            EnvironmentalScore: 1.0246457001441578
            ProductID:
            - ProductID
            - ProductID
            BaseScore: 7.386281948385884
            Vector: Vector
          - TemporalScore: 1.2315135367772556
            EnvironmentalScore: 1.0246457001441578
            ProductID:
            - ProductID
            - ProductID
            BaseScore: 7.386281948385884
            Vector: Vector
          Acknowledgments:
          - Organization:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
            Description:
              Value: Value
              lang: lang
            URL:
            - URL
            - URL
            Name:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
          - Organization:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
            Description:
              Value: Value
              lang: lang
            URL:
            - URL
            - URL
            Name:
            - Value: Value
              lang: lang
            - Value: Value
              lang: lang
          DiscoveryDate: 2000-01-23T04:56:07.000+00:00
          RevisionHistory:
          - Description:
              Value: Value
              lang: lang
            Number: Number
            Date: 2000-01-23T04:56:07.000+00:00
          - Description:
              Value: Value
              lang: lang
            Number: Number
            Date: 2000-01-23T04:56:07.000+00:00
          References:
          - Type: 6
            Description:
              Value: Value
              lang: lang
            URL: URL
          - Type: 6
            Description:
              Value: Value
              lang: lang
            URL: URL
          Ordinal: Ordinal
          DiscoveryDateSpecified: true
          ID:
            Value: Value
            SystemName: SystemName
          Notes:
          - Type: 7
            Audience: Audience
            Ordinal: Ordinal
            Value: Value
            Title: Title
            lang: lang
          - Type: 7
            Audience: Audience
            Ordinal: Ordinal
            Value: Value
            Title: Title
            lang: lang
        DocumentTitle:
          Value: Value
          lang: lang
        ProductTree:
          Branch:
          - Type: 5
            Items:
            - '{}'
            - '{}'
            Name: Name
          - Type: 5
            Items:
            - '{}'
            - '{}'
            Name: Name
          Relationship:
          - RelatesToProductReference: RelatesToProductReference
            ProductReference: ProductReference
            RelationType: 2
            FullProductName:
            - Value: Value
              CPE: CPE
              ProductID: ProductID
            - Value: Value
              CPE: CPE
              ProductID: ProductID
          - RelatesToProductReference: RelatesToProductReference
            ProductReference: ProductReference
            RelationType: 2
            FullProductName:
            - Value: Value
              CPE: CPE
              ProductID: ProductID
            - Value: Value
              CPE: CPE
              ProductID: ProductID
          FullProductName:
          - Value: Value
            CPE: CPE
            ProductID: ProductID
          - Value: Value
            CPE: CPE
            ProductID: ProductID
          ProductGroups:
          - Description:
              Value: Value
              lang: lang
            ProductID:
            - ProductID
            - ProductID
            GroupID: GroupID
          - Description:
              Value: Value
              lang: lang
            ProductID:
            - ProductID
            - ProductID
            GroupID: GroupID
        DocumentTracking:
          Status: 6
          Version: Version
          RevisionHistory:
          - Description:
              Value: Value
              lang: lang
            Number: Number
            Date: 2000-01-23T04:56:07.000+00:00
          - Description:
              Value: Value
              lang: lang
            Number: Number
            Date: 2000-01-23T04:56:07.000+00:00
          Identification:
            Alias:
              Value: Value
              lang: lang
            ID:
              Value: Value
              lang: lang
          CurrentReleaseDate: 2000-01-23T04:56:07.000+00:00
          InitialReleaseDate: 2000-01-23T04:56:07.000+00:00
          Generator:
            DateSpecified: true
            Engine:
              Value: Value
              lang: lang
            Date: 2000-01-23T04:56:07.000+00:00
        DocumentReferences:
        - Type: 5
          Description:
            Value: Value
            lang: lang
          URL: URL
        - Type: 5
          Description:
            Value: Value
            lang: lang
          URL: URL
      properties:
        DocumentTitle:
          $ref: '#/components/schemas/cvrfdocDocumentTitle'
        DocumentType:
          $ref: '#/components/schemas/cvrfdocDocumentType'
        DocumentPublisher:
          $ref: '#/components/schemas/cvrfdocDocumentPublisher'
        DocumentTracking:
          $ref: '#/components/schemas/cvrfdocDocumentTracking'
        DocumentNotes:
          items:
            $ref: '#/components/schemas/cvrfdocNote'
          type: array
        DocumentDistribution:
          $ref: '#/components/schemas/cvrfdocDocumentDistribution'
        AggregateSeverity:
          $ref: '#/components/schemas/cvrfdocAggregateSeverity'
        DocumentReferences:
          items:
            $ref: '#/components/schemas/cvrfdocReference'
          type: array
        Acknowledgments:
          items:
            $ref: '#/components/schemas/cvrfdocAcknowledgment'
          type: array
        ProductTree:
          $ref: '#/components/schemas/ProductTree'
        Vulnerability:
          items:
            $ref: '#/components/schemas/Vulnerability'
          type: array
      type: object
    cvrfdocDocumentTitle:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocDocumentType:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocDocumentPublisher:
      example:
        Type: 0
        ContactDetails:
          Value: Value
          lang: lang
        VendorID: VendorID
        IssuingAuthority:
          Value: Value
          lang: lang
      properties:
        ContactDetails:
          $ref: '#/components/schemas/cvrfdocDocumentPublisherContactDetails'
        IssuingAuthority:
          $ref: '#/components/schemas/cvrfdocDocumentPublisherIssuingAuthority'
        Type:
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          format: int32
          type: integer
        VendorID:
          type: string
      type: object
    cvrfdocDocumentTracking:
      example:
        Status: 6
        Version: Version
        RevisionHistory:
        - Description:
            Value: Value
            lang: lang
          Number: Number
          Date: 2000-01-23T04:56:07.000+00:00
        - Description:
            Value: Value
            lang: lang
          Number: Number
          Date: 2000-01-23T04:56:07.000+00:00
        Identification:
          Alias:
            Value: Value
            lang: lang
          ID:
            Value: Value
            lang: lang
        CurrentReleaseDate: 2000-01-23T04:56:07.000+00:00
        InitialReleaseDate: 2000-01-23T04:56:07.000+00:00
        Generator:
          DateSpecified: true
          Engine:
            Value: Value
            lang: lang
          Date: 2000-01-23T04:56:07.000+00:00
      properties:
        Identification:
          $ref: '#/components/schemas/cvrfdocDocumentTrackingIdentification'
        Status:
          enum:
          - 0
          - 1
          - 2
          format: int32
          type: integer
        Version:
          type: string
        RevisionHistory:
          items:
            $ref: '#/components/schemas/cvrfdocDocumentTrackingRevision'
          type: array
        InitialReleaseDate:
          format: date-time
          type: string
        CurrentReleaseDate:
          format: date-time
          type: string
        Generator:
          $ref: '#/components/schemas/cvrfdocDocumentTrackingGenerator'
      type: object
    cvrfdocNote:
      example:
        Type: 1
        Audience: Audience
        Ordinal: Ordinal
        Value: Value
        Title: Title
        lang: lang
      properties:
        Title:
          type: string
        Audience:
          type: string
        Type:
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          format: int32
          type: integer
        Ordinal:
          type: string
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocDocumentDistribution:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocAggregateSeverity:
      example:
        Value: Value
        lang: lang
        Namespace: Namespace
      properties:
        Namespace:
          type: string
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocReference:
      example:
        Type: 5
        Description:
          Value: Value
          lang: lang
        URL: URL
      properties:
        URL:
          type: string
        Description:
          $ref: '#/components/schemas/cvrfdocReferenceDescription'
        Type:
          enum:
          - 0
          - 1
          format: int32
          type: integer
      type: object
    cvrfdocAcknowledgment:
      example:
        Organization:
        - Value: Value
          lang: lang
        - Value: Value
          lang: lang
        Description:
          Value: Value
          lang: lang
        URL:
        - URL
        - URL
        Name:
        - Value: Value
          lang: lang
        - Value: Value
          lang: lang
      properties:
        Name:
          items:
            $ref: '#/components/schemas/cvrfdocAcknowledgmentName'
          type: array
        Organization:
          items:
            $ref: '#/components/schemas/cvrfdocAcknowledgmentOrganization'
          type: array
        Description:
          $ref: '#/components/schemas/cvrfdocAcknowledgmentDescription'
        URL:
          items:
            type: string
          type: array
      type: object
    ProductTree:
      example:
        Branch:
        - Type: 5
          Items:
          - '{}'
          - '{}'
          Name: Name
        - Type: 5
          Items:
          - '{}'
          - '{}'
          Name: Name
        Relationship:
        - RelatesToProductReference: RelatesToProductReference
          ProductReference: ProductReference
          RelationType: 2
          FullProductName:
          - Value: Value
            CPE: CPE
            ProductID: ProductID
          - Value: Value
            CPE: CPE
            ProductID: ProductID
        - RelatesToProductReference: RelatesToProductReference
          ProductReference: ProductReference
          RelationType: 2
          FullProductName:
          - Value: Value
            CPE: CPE
            ProductID: ProductID
          - Value: Value
            CPE: CPE
            ProductID: ProductID
        FullProductName:
        - Value: Value
          CPE: CPE
          ProductID: ProductID
        - Value: Value
          CPE: CPE
          ProductID: ProductID
        ProductGroups:
        - Description:
            Value: Value
            lang: lang
          ProductID:
          - ProductID
          - ProductID
          GroupID: GroupID
        - Description:
            Value: Value
            lang: lang
          ProductID:
          - ProductID
          - ProductID
          GroupID: GroupID
      properties:
        Branch:
          items:
            $ref: '#/components/schemas/BranchType'
          type: array
        FullProductName:
          items:
            $ref: '#/components/schemas/FullProductName'
          type: array
        Relationship:
          items:
            $ref: '#/components/schemas/ProductTreeRelationship'
          type: array
        ProductGroups:
          items:
            $ref: '#/components/schemas/ProductTreeGroup'
          type: array
      type: object
    Vulnerability:
      example:
        Threats:
        - Type: 4
          Description:
            Value: Value
            lang: lang
          ProductID:
          - ProductID
          - ProductID
          DateSpecified: true
          Date: 2000-01-23T04:56:07.000+00:00
          GroupID:
          - GroupID
          - GroupID
        - Type: 4
          Description:
            Value: Value
            lang: lang
          ProductID:
          - ProductID
          - ProductID
          DateSpecified: true
          Date: 2000-01-23T04:56:07.000+00:00
          GroupID:
          - GroupID
          - GroupID
        Involvements:
        - Status: 3
          Description:
            Value: Value
            lang: lang
          Party: 9
        - Status: 3
          Description:
            Value: Value
            lang: lang
          Party: 9
        ProductStatuses:
        - Type: 2
          ProductID:
          - ProductID
          - ProductID
        - Type: 2
          ProductID:
          - ProductID
          - ProductID
        ReleaseDateSpecified: true
        Title:
          Value: Value
          lang: lang
        Remediations:
        - Description:
            Value: Value
            lang: lang
          RestartRequired:
            Value: Value
            lang: lang
          SubType: SubType
          AffectedFiles:
          - FilePath: FilePath
            FileArchitecture: FileArchitecture
            FileName: FileName
            FileVersion: FileVersion
            FileLastModified: 2000-01-23T04:56:07.000+00:00
            ProductId: ProductId
          - FilePath: FilePath
            FileArchitecture: FileArchitecture
            FileName: FileName
            FileVersion: FileVersion
            FileLastModified: 2000-01-23T04:56:07.000+00:00
            ProductId: ProductId
          Supercedence: Supercedence
          ProductID:
          - ProductID
          - ProductID
          DateSpecified: true
          URL: URL
          Date: 2000-01-23T04:56:07.000+00:00
          GroupID:
          - GroupID
          - GroupID
          Type: 1
          Entitlement:
          - Value: Value
            lang: lang
          - Value: Value
            lang: lang
          FixedBuild: FixedBuild
        - Description:
            Value: Value
            lang: lang
          RestartRequired:
            Value: Value
            lang: lang
          SubType: SubType
          AffectedFiles:
          - FilePath: FilePath
            FileArchitecture: FileArchitecture
            FileName: FileName
            FileVersion: FileVersion
            FileLastModified: 2000-01-23T04:56:07.000+00:00
            ProductId: ProductId
          - FilePath: FilePath
            FileArchitecture: FileArchitecture
            FileName: FileName
            FileVersion: FileVersion
            FileLastModified: 2000-01-23T04:56:07.000+00:00
            ProductId: ProductId
          Supercedence: Supercedence
          ProductID:
          - ProductID
          - ProductID
          DateSpecified: true
          URL: URL
          Date: 2000-01-23T04:56:07.000+00:00
          GroupID:
          - GroupID
          - GroupID
          Type: 1
          Entitlement:
          - Value: Value
            lang: lang
          - Value: Value
            lang: lang
          FixedBuild: FixedBuild
        ReleaseDate: 2000-01-23T04:56:07.000+00:00
        CWE:
        - Value: Value
          ID: ID
          lang: lang
        - Value: Value
          ID: ID
          lang: lang
        CVE: CVE
        CVSSScoreSets:
        - TemporalScore: 1.2315135367772556
          EnvironmentalScore: 1.0246457001441578
          ProductID:
          - ProductID
          - ProductID
          BaseScore: 7.386281948385884
          Vector: Vector
        - TemporalScore: 1.2315135367772556
          EnvironmentalScore: 1.0246457001441578
          ProductID:
          - ProductID
          - ProductID
          BaseScore: 7.386281948385884
          Vector: Vector
        Acknowledgments:
        - Organization:
          - Value: Value
            lang: lang
          - Value: Value
            lang: lang
          Description:
            Value: Value
            lang: lang
          URL:
          - URL
          - URL
          Name:
          - Value: Value
            lang: lang
          - Value: Value
            lang: lang
        - Organization:
          - Value: Value
            lang: lang
          - Value: Value
            lang: lang
          Description:
            Value: Value
            lang: lang
          URL:
          - URL
          - URL
          Name:
          - Value: Value
            lang: lang
          - Value: Value
            lang: lang
        DiscoveryDate: 2000-01-23T04:56:07.000+00:00
        RevisionHistory:
        - Description:
            Value: Value
            lang: lang
          Number: Number
          Date: 2000-01-23T04:56:07.000+00:00
        - Description:
            Value: Value
            lang: lang
          Number: Number
          Date: 2000-01-23T04:56:07.000+00:00
        References:
        - Type: 6
          Description:
            Value: Value
            lang: lang
          URL: URL
        - Type: 6
          Description:
            Value: Value
            lang: lang
          URL: URL
        Ordinal: Ordinal
        DiscoveryDateSpecified: true
        ID:
          Value: Value
          SystemName: SystemName
        Notes:
        - Type: 7
          Audience: Audience
          Ordinal: Ordinal
          Value: Value
          Title: Title
          lang: lang
        - Type: 7
          Audience: Audience
          Ordinal: Ordinal
          Value: Value
          Title: Title
          lang: lang
      properties:
        Title:
          $ref: '#/components/schemas/VulnerabilityTitle'
        ID:
          $ref: '#/components/schemas/VulnerabilityID'
        Notes:
          items:
            $ref: '#/components/schemas/VulnerabilityNote'
          type: array
        DiscoveryDate:
          format: date-time
          type: string
        DiscoveryDateSpecified:
          type: boolean
        ReleaseDate:
          format: date-time
          type: string
        ReleaseDateSpecified:
          type: boolean
        Involvements:
          items:
            $ref: '#/components/schemas/VulnerabilityInvolvement'
          type: array
        CVE:
          type: string
        CWE:
          items:
            $ref: '#/components/schemas/VulnerabilityCWE'
          type: array
        ProductStatuses:
          items:
            $ref: '#/components/schemas/VulnerabilityStatus'
          type: array
        Threats:
          items:
            $ref: '#/components/schemas/VulnerabilityThreat'
          type: array
        CVSSScoreSets:
          items:
            $ref: '#/components/schemas/VulnerabilityScoreSet'
          type: array
        Remediations:
          items:
            $ref: '#/components/schemas/VulnerabilityRemediation'
          type: array
        References:
          items:
            $ref: '#/components/schemas/VulnerabilityReference'
          type: array
        Acknowledgments:
          items:
            $ref: '#/components/schemas/VulnerabilityAcknowledgment'
          type: array
        Ordinal:
          type: string
        RevisionHistory:
          items:
            $ref: '#/components/schemas/cvrfdocDocumentTrackingRevision'
          type: array
      type: object
    cvrfdocDocumentPublisherContactDetails:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocDocumentPublisherIssuingAuthority:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocDocumentTrackingIdentification:
      example:
        Alias:
          Value: Value
          lang: lang
        ID:
          Value: Value
          lang: lang
      properties:
        ID:
          $ref: '#/components/schemas/cvrfdocDocumentTrackingIdentificationID'
        Alias:
          $ref: '#/components/schemas/cvrfdocDocumentTrackingIdentificationAlias'
      type: object
    cvrfdocDocumentTrackingRevision:
      example:
        Description:
          Value: Value
          lang: lang
        Number: Number
        Date: 2000-01-23T04:56:07.000+00:00
      properties:
        Number:
          type: string
        Date:
          format: date-time
          type: string
        Description:
          $ref: '#/components/schemas/cvrfdocDocumentTrackingRevisionDescription'
      type: object
    cvrfdocDocumentTrackingGenerator:
      example:
        DateSpecified: true
        Engine:
          Value: Value
          lang: lang
        Date: 2000-01-23T04:56:07.000+00:00
      properties:
        Engine:
          $ref: '#/components/schemas/cvrfdocDocumentTrackingGeneratorEngine'
        Date:
          format: date-time
          type: string
        DateSpecified:
          type: boolean
      type: object
    cvrfdocReferenceDescription:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocAcknowledgmentName:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocAcknowledgmentOrganization:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocAcknowledgmentDescription:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    BranchType:
      example:
        Type: 5
        Items:
        - '{}'
        - '{}'
        Name: Name
      properties:
        Items:
          items:
            properties: {}
            type: object
          type: array
        Type:
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          format: int32
          type: integer
        Name:
          type: string
      type: object
    FullProductName:
      example:
        Value: Value
        CPE: CPE
        ProductID: ProductID
      properties:
        ProductID:
          type: string
        CPE:
          type: string
        Value:
          type: string
      type: object
    ProductTreeRelationship:
      example:
        RelatesToProductReference: RelatesToProductReference
        ProductReference: ProductReference
        RelationType: 2
        FullProductName:
        - Value: Value
          CPE: CPE
          ProductID: ProductID
        - Value: Value
          CPE: CPE
          ProductID: ProductID
      properties:
        FullProductName:
          items:
            $ref: '#/components/schemas/FullProductName'
          type: array
        ProductReference:
          type: string
        RelationType:
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          format: int32
          type: integer
        RelatesToProductReference:
          type: string
      type: object
    ProductTreeGroup:
      example:
        Description:
          Value: Value
          lang: lang
        ProductID:
        - ProductID
        - ProductID
        GroupID: GroupID
      properties:
        Description:
          $ref: '#/components/schemas/ProductTreeGroupDescription'
        ProductID:
          items:
            type: string
          type: array
        GroupID:
          type: string
      type: object
    VulnerabilityTitle:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityID:
      example:
        Value: Value
        SystemName: SystemName
      properties:
        SystemName:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityNote:
      example:
        Type: 7
        Audience: Audience
        Ordinal: Ordinal
        Value: Value
        Title: Title
        lang: lang
      properties:
        Title:
          type: string
        Audience:
          type: string
        Type:
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          format: int32
          type: integer
        Ordinal:
          type: string
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityInvolvement:
      example:
        Status: 3
        Description:
          Value: Value
          lang: lang
        Party: 9
      properties:
        Description:
          $ref: '#/components/schemas/VulnerabilityInvolvementDescription'
        Party:
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          format: int32
          type: integer
        Status:
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          format: int32
          type: integer
      type: object
    VulnerabilityCWE:
      example:
        Value: Value
        ID: ID
        lang: lang
      properties:
        ID:
          type: string
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityStatus:
      example:
        Type: 2
        ProductID:
        - ProductID
        - ProductID
      properties:
        ProductID:
          items:
            type: string
          type: array
        Type:
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          format: int32
          type: integer
      type: object
    VulnerabilityThreat:
      example:
        Type: 4
        Description:
          Value: Value
          lang: lang
        ProductID:
        - ProductID
        - ProductID
        DateSpecified: true
        Date: 2000-01-23T04:56:07.000+00:00
        GroupID:
        - GroupID
        - GroupID
      properties:
        Description:
          $ref: '#/components/schemas/VulnerabilityThreatDescription'
        ProductID:
          items:
            type: string
          type: array
        GroupID:
          items:
            type: string
          type: array
        Type:
          enum:
          - 0
          - 1
          - 2
          - 3
          format: int32
          type: integer
        Date:
          format: date-time
          type: string
        DateSpecified:
          type: boolean
      type: object
    VulnerabilityScoreSet:
      example:
        TemporalScore: 1.2315135367772556
        EnvironmentalScore: 1.0246457001441578
        ProductID:
        - ProductID
        - ProductID
        BaseScore: 7.386281948385884
        Vector: Vector
      properties:
        BaseScore:
          format: double
          type: number
        TemporalScore:
          format: double
          type: number
        EnvironmentalScore:
          format: double
          type: number
        Vector:
          type: string
        ProductID:
          items:
            type: string
          type: array
      type: object
    VulnerabilityRemediation:
      example:
        Description:
          Value: Value
          lang: lang
        RestartRequired:
          Value: Value
          lang: lang
        SubType: SubType
        AffectedFiles:
        - FilePath: FilePath
          FileArchitecture: FileArchitecture
          FileName: FileName
          FileVersion: FileVersion
          FileLastModified: 2000-01-23T04:56:07.000+00:00
          ProductId: ProductId
        - FilePath: FilePath
          FileArchitecture: FileArchitecture
          FileName: FileName
          FileVersion: FileVersion
          FileLastModified: 2000-01-23T04:56:07.000+00:00
          ProductId: ProductId
        Supercedence: Supercedence
        ProductID:
        - ProductID
        - ProductID
        DateSpecified: true
        URL: URL
        Date: 2000-01-23T04:56:07.000+00:00
        GroupID:
        - GroupID
        - GroupID
        Type: 1
        Entitlement:
        - Value: Value
          lang: lang
        - Value: Value
          lang: lang
        FixedBuild: FixedBuild
      properties:
        Description:
          $ref: '#/components/schemas/VulnerabilityRemediationDescription'
        Entitlement:
          items:
            $ref: '#/components/schemas/VulnerabilityRemediationEntitlement'
          type: array
        URL:
          type: string
        Supercedence:
          type: string
        ProductID:
          items:
            type: string
          type: array
        GroupID:
          items:
            type: string
          type: array
        Type:
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          format: int32
          type: integer
        Date:
          format: date-time
          type: string
        DateSpecified:
          type: boolean
        AffectedFiles:
          items:
            $ref: '#/components/schemas/AffectedFile'
          type: array
        RestartRequired:
          $ref: '#/components/schemas/VulnerabilityRemediationRestartRequired'
        SubType:
          type: string
        FixedBuild:
          type: string
      type: object
    VulnerabilityReference:
      example:
        Type: 6
        Description:
          Value: Value
          lang: lang
        URL: URL
      properties:
        URL:
          type: string
        Description:
          $ref: '#/components/schemas/VulnerabilityReferenceDescription'
        Type:
          enum:
          - 0
          - 1
          format: int32
          type: integer
      type: object
    VulnerabilityAcknowledgment:
      example:
        Organization:
        - Value: Value
          lang: lang
        - Value: Value
          lang: lang
        Description:
          Value: Value
          lang: lang
        URL:
        - URL
        - URL
        Name:
        - Value: Value
          lang: lang
        - Value: Value
          lang: lang
      properties:
        Name:
          items:
            $ref: '#/components/schemas/VulnerabilityAcknowledgmentName'
          type: array
        Organization:
          items:
            $ref: '#/components/schemas/VulnerabilityAcknowledgmentOrganization'
          type: array
        Description:
          $ref: '#/components/schemas/VulnerabilityAcknowledgmentDescription'
        URL:
          items:
            type: string
          type: array
      type: object
    cvrfdocDocumentTrackingIdentificationID:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocDocumentTrackingIdentificationAlias:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocDocumentTrackingRevisionDescription:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    cvrfdocDocumentTrackingGeneratorEngine:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    ProductTreeGroupDescription:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityInvolvementDescription:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityThreatDescription:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityRemediationDescription:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityRemediationEntitlement:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    AffectedFile:
      example:
        FilePath: FilePath
        FileArchitecture: FileArchitecture
        FileName: FileName
        FileVersion: FileVersion
        FileLastModified: 2000-01-23T04:56:07.000+00:00
        ProductId: ProductId
      properties:
        ProductId:
          type: string
        FileName:
          type: string
        FileVersion:
          type: string
        FilePath:
          type: string
        FileLastModified:
          format: date-time
          type: string
        FileArchitecture:
          type: string
      type: object
    VulnerabilityRemediationRestartRequired:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityReferenceDescription:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityAcknowledgmentName:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityAcknowledgmentOrganization:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    VulnerabilityAcknowledgmentDescription:
      example:
        Value: Value
        lang: lang
      properties:
        lang:
          type: string
        Value:
          type: string
      type: object
    Update:
      description: summary information about a security release (CVRF document)
      example:
        Alias: Alias
        Severity: Severity
        ID: ID
        CvrfUrl: CvrfUrl
        DocumentTitle: DocumentTitle
        CurrentReleaseDate: 2000-01-23T04:56:07.000+00:00
        InitialReleaseDate: 2000-01-23T04:56:07.000+00:00
      properties:
        ID:
          description: unique identifier for CVRF document, often yyyy-mmm
          type: string
        Alias:
          description: alternative ID for CVRF document
          type: string
        DocumentTitle:
          description: title of CVRF document
          type: string
        Severity:
          description: aggregate severity
          type: string
        InitialReleaseDate:
          description: date that the CVRF document was initially released
          format: date-time
          type: string
        CurrentReleaseDate:
          description: date that the CVRF document was last modified
          format: date-time
          type: string
        CvrfUrl:
          description: URL of CVRF document (for CVRF endpoint)
          type: string
      required:
      - Alias
      - CurrentReleaseDate
      - CvrfUrl
      - DocumentTitle
      - ID
      - InitialReleaseDate
      type: object
    inline_response_200:
      example:
        '@odata.context': http://example.com/aeiou
        value:
        - Alias: Alias
          Severity: Severity
          ID: ID
          CvrfUrl: CvrfUrl
          DocumentTitle: DocumentTitle
          CurrentReleaseDate: 2000-01-23T04:56:07.000+00:00
          InitialReleaseDate: 2000-01-23T04:56:07.000+00:00
        - Alias: Alias
          Severity: Severity
          ID: ID
          CvrfUrl: CvrfUrl
          DocumentTitle: DocumentTitle
          CurrentReleaseDate: 2000-01-23T04:56:07.000+00:00
          InitialReleaseDate: 2000-01-23T04:56:07.000+00:00
      properties:
        '@odata.context':
          description: OData metadata for the request
          format: url
          type: string
        value:
          description: array of security update summaries
          items:
            $ref: '#/components/schemas/Update'
          type: array
      required:
      - '@odata.context'
      - value
      type: object
x-original-swagger-version: "2.0"
